### PR TITLE
support generics for simple cases

### PR DESCRIPTION
**Pull request by a8t3r**

### CODE REVIEW

**Comment by arnaudroger** [comment]
Thanks, I'll put that asap in 1.5.1. 

For the Pair it should work if you pass a ParameterizedType
the Tuples class as a can return those 
Tuples.tupleImplementationTypeDef(Pair.class, String.class, Long.class)

**Comment by a8t3r** [comment]
unfortunately Pair<T,V> with ParameterizedType doesn't work.
Class meta data resolver ReflectionService.getClassMeta returns TupleClassMeta for tuples and ObjectClassMeta for others - they have different .newPropertyFinder implementations

**Comment by arnaudroger** [comment]
the main difference between tuples and object metadata is that tuples is using index lookup, object meta data need a match on the name of the property.
The way to creates a TuplesMetaData right now is quite static... 
I could use annotation to mark it as a tuple class? or using some registration in the Tuples class?

**Comment by a8t3r** [comment]
i think, there's no need in for explicit tuple registration - please review #111

**Pull request merged**
